name = "SortedIteratorProducts"
uuid = "6df855aa-0571-4a39-928e-ca59f790d640"
authors = ["Lilith Hafner <Lilith.Hafner@gmail.com> and contributors"]
version = "0.0.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[targets]
test = ["Test", "StatsBase"]
